### ISSUE TITLE
Review new GridAPPS-D Architecture description

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-hackathon#24]
Review new GridAPPS-D Architecture description
* overview / Notebook 2.2
* https://gridappsd-training.readthedocs.io/en/latest/overview/2.2-GridAPPS-D-Architecture.html

**Comment by MuMonish** [comment]
**2.2-GridAPPS-D-Architecture**: Quiz-for-Lesson-2.2 requires content.
**2.3-GridAPPS-D-Python-Library**: Quiz-for-Lesson-2.3 requires content.
**2.4-GridAPPS-D-Application-Structure**: Quiz-for-Lesson-2.4 requires content.
**2.5-GridAPPS-D-Service-Structure**: Quiz-for-Lesson-2.5 requires content.
**2.6-Common-Information-Model**: Quiz-for-Lesson-2.6 requires content.

**2.5-GridAPPS-D-Service-Structure**: Module 2.5 requires content.
