### ISSUE TITLE
Review API Topic & Message structure sections

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-hackathon#26]
Review sections on GridAPPS-D API topics and messages:
* Notebook 3.1, https://gridappsd-training.readthedocs.io/en/latest/api_usage/3.1-API-Communication-Channels.html
* Notebook 3.2, https://gridappsd-training.readthedocs.io/en/latest/api_usage/3.2-API-Message-Structure.html

**Comment by MuMonish** [comment]
The landing page for Module 3 does not list all the sub modules along with a brief intro to individual sub-module (adding a tentative list for review).

**Comment by MuMonish** [comment]
**3.1-API-Communication-Channels**: Some of the sub-bullets (given below) listed in the **Table of Contents** has no content linked to them. 
> - 4.4. Subscribe to Application Output
> - 4.5. Publish to Application Input
> - 4.6. Subscribe to Service Output
> - 4.7. Publish to Service Input

Suggestion: It will be good to add a jupyter cell with ready-to-test sample queries/message for
> - Request Timeseries Data
> - Request Platform Status
> - Querying Log Data
> - Subscribing to Platform Logs

**3.2-API-Message-Structure:** Quiz-for-Lesson-3.2 requires content.
