### ISSUE TITLE
Review PowerGrid Models API section

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-hackathon#28]
Review new refactored version of PowerGrid Models API docs:
* Notebook 3.3
* https://gridappsd-training.readthedocs.io/en/latest/api_usage/3.3-Using-the-PowerGrid-Models-API.html

**Comment by MuMonish** [comment]
**3.3-Using-the-PowerGrid-Models-API**: Quiz-for-Lesson-3.3 requires content.
