### ISSUE TITLE
Review Configuration File API section

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-hackathon#29]
Review Configuration File API section:
* Notebook 3.4
* https://gridappsd-training.readthedocs.io/en/latest/api_usage/3.4-Using-the-Configuration-File-API.html

**Comment by MuMonish** [comment]
**Sample Query** to _Export IEEE 13 node model with constant current loads to GLM files_  returns: blank _data_ key and _java.lang.NullPointerException_ in the terminal

**Comment by MuMonish** [comment]
**3.4-Using-the-Configuration-File-API**
-  **3.4. Query for GridLab-D Measurement Types**:  Some more information about how to get the **simulation_id** would help the users. This got cleared to me in Lesson _3.5-Creating-Running-Simulation-API: Starting the Simulation_ that the can be obtained using: 

> simulation_id = simulation_obj.simulation_id # Obtain Simulation ID
> print("Successfully started simulation with simulation_id: ", simulation_id)

- Quiz-for-Lesson-3.4 requires content.
