### ISSUE TITLE
Documentation of installation issues when connected to VPN

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-hackathon#3]
Add note to readthedocs and python notebooks that should not be connected to a corporate VPN when trying to clone GitHub repos

**Comment by AAndersn** [comment]
@poorva1209 - Do we need to include images of the error as well?

https://gridappsd-training.readthedocs.io/en/develop/installation/windows10/1.2W-Installing-GridAPPS-D.html#Known-Issues-around-Corporate-VPN-Connectivity

**Comment by AAndersn** [comment]
@tonya1 or @poorva1209 , please review and close 

https://gridappsd-training.readthedocs.io/en/develop/installation/1.9-Known-VPN-Proxy-Issues.html

**Comment by tonya1** [comment]
Looks great.  Thank you.
