### ISSUE TITLE
Review Simulation API sections

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-hackathon#30]
Review Simulation API sections

Creating and running simulations:
* Notebook 3.5
* https://gridappsd-training.readthedocs.io/en/latest/api_usage/3.5-Creating-Running-Simulation-API.html

Publishing and subscribing:
* Notebook 3.6
* https://gridappsd-training.readthedocs.io/en/latest/api_usage/3.6-Controlling-Simulation-API.html

**Comment by MuMonish** [comment]
**3.5-Creating-Running-Simulation-API**
- Quiz-for-Lesson-3.5 requires content.

**3.7-Using-the-Timeseries-API** 

> **3.4.2. Querying Sensor Service Data** -  The query for _gridappsd-sensor-simulator_ , given in example 1, doesn't return any outputs (may be the mrids in "_Run123NodeSensorServiceDemo.py_" file are not up-to-date).
