### ISSUE TITLE
Need descriptions of user roles

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-hackathon#4]
Need descriptions of user roles

What role is used for

Who would use this role - application, viz user, platform, etc

What are permissions given to this role

**Comment by AAndersn** [comment]
@tdtalbot , if you can send them as plain text by email, I'll be able to put them into training notebooks

**Comment by AAndersn** [comment]
@bibiraju , please review and close

https://gridappsd-training.readthedocs.io/en/develop/overview/2.2-GridAPPS-D-Architecture.html#GridAPPS-D-User-Roles

**Comment by bibiraju** [comment]
Closing the issue after reviewing the document.
